# Generated by Django 3.2.7 on 2021-11-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='my_field',
        ),
    ]
