# Generated by Django 3.2.7 on 2021-11-23 08:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_remove_document_my_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='Item title 1.1', max_length=49),
            preserve_default=False,
        ),
    ]
