# Generated by Django 3.2.7 on 2021-11-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_document_my_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='my_field',
            new_name='tag',
        ),
    ]
