# Generated by Django 3.2.9 on 2021-11-27 02:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_rename_my_field_document_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Công nghệ thông tin', 'Công nghệ thông tin'), ('Điện tử', 'Điện tử'), ('Cơ khí', 'Cơ khí'), ('Khoa học máy tính', 'Khoa học máy tính'), ('Phần mềm', 'Phần mềm')], max_length=61),
        ),
    ]
